Repository SU-SWS/stanford_publication, pull requests merged in 2021-03, with the labels that each got.

#28 D8CORE-3520 Create publications list page
  composer.json
  config/install/core.entity_view_display.node.stanford_publication.default.yml
  config/install/system.menu.stanford-publication-topics.yml
  config/install/taxonomy_menu.taxonomy_menu.publication_topics.yml
  config/install/views.view.stanford_publications.yml
  dist/assets/svg/caret-down.svg
  dist/css/component/menu/taxonomy_menu.css
  dist/css/component/views/stanford_publication.css
  lib/scss/component/menu/taxonomy_menu.scss
  lib/scss/component/views/stanford_publication.scss
  package-lock.json
  src/CitationTypeAccessControlHandler.php
  src/CitationViewBuilder.php
  src/Entity/Citation.php
  src/Entity/CitationType.php
  stanford_publication.info.yml
  stanford_publication.module
  tests/src/Kernel/CitationTypeAccessControlHandlerTest.php
  tests/src/Kernel/CitationViewBuilderTest.php
Labels: patch, size/s

#29 "8.x-1.x 8.1.2
  CHANGELOG.md
  composer.json
  config/install/core.entity_view_display.node.stanford_publication.default.yml
  config/install/system.menu.stanford-publication-topics.yml
  config/install/taxonomy_menu.taxonomy_menu.publication_topics.yml
  config/install/views.view.stanford_publications.yml
  dist/assets/svg/caret-down.svg
  dist/css/component/menu/taxonomy_menu.css
  dist/css/component/node/stanford_publication.css
  dist/css/component/views/stanford_publication.css
  lib/scss/component/menu/taxonomy_menu.scss
  lib/scss/component/node/stanford_publication.scss
  lib/scss/component/views/stanford_publication.scss
  package-lock.json
  src/CitationTypeAccessControlHandler.php
  src/CitationViewBuilder.php
  src/Entity/Citation.php
  src/Entity/CitationType.php
  stanford_publication.info.yml
  stanford_publication.module
  tests/src/Kernel/CitationTypeAccessControlHandlerTest.php
  tests/src/Kernel/CitationViewBuilderTest.php
Labels: patch, size/l

#30 8.1.3
  composer.json
  stanford_publication.info.yml
Labels: patch, size/xs

#31 D8CORE-3948: fix to the more publication cards and added the see all …
  CHANGELOG.md
  dist/css/component/views/stanford_publication.css
  lib/scss/component/views/stanford_publication.scss
  stanford_publication.info.yml
Labels: patch, size/xs

#33 D8CORE-3536 Add pseudo field for easily displaying the citation type
  config/install/core.entity_view_display.node.stanford_publication.default.yml
  stanford_publication.module
Labels: size/xs

#34 D8CORE-3952 Create the "All" topic term
  stanford_publication.info.yml
  stanford_publication.install
  tests/codeception/acceptance/PublicationsCest.php
Labels: patch, size/xs

#36 Suggested changes
  dist/css/component/menu/taxonomy_menu.css
  dist/js/stanford_publication.behavior.js
  dist/js/stanford_publication.behavior.js.map
  dist/js/stanford_publication.js
  dist/js/stanford_publication.js.map
  lib/js/stanford_publication.behavior.js
  lib/scss/component/menu/taxonomy_menu.scss
Labels: size/xs

#35 D8CORE-3538 Change "Other" to "Publication"
  src/Form/CitationTypeForm.php
  stanford_publication.module
Labels: size/xs
