Repository SU-SWS/stanford_publication, pull requests merged in 2021-09, with the labels that each got.

#47 D8CORE-3161: moving the pager to the theme
  dist/css/component/views/stanford_publication.css
  lib/scss/component/views/stanford_publication.scss
Labels: size/xs

#48 8.1.8
  CHANGELOG.md
  dist/css/component/views/stanford_publication.css
  lib/scss/component/views/stanford_publication.scss
  src/CitationViewBuilder.php
  stanford_publication.info.yml
  tests/src/Kernel/CitationViewBuilderTest.php
Labels: patch, size/xs

#49 D8CORE-4770: fix to the publication lists
  dist/css/component/views/stanford_publication.css
  lib/scss/component/views/stanford_publication.scss
Labels: size/xs

#50 8.1.9
  CHANGELOG.md
  dist/css/component/views/stanford_publication.css
  lib/scss/component/views/stanford_publication.scss
  stanford_publication.info.yml
Labels: patch, size/xs

#51 D8CORE-3749 Publications csv importer
  config/optional/migrate_plus.migration.stanford_publications.yml
Labels: size/s
