Repository SU-SWS/stanford_publication, pull requests merged in 2021-02, with the labels that each got.

#23 D8CORE-3445: tweaking the label names and hiding extra fields
  config/install/core.entity_view_display.citation.su_article_journal.default.yml
  config/install/core.entity_view_display.citation.su_article_newspaper.default.yml
  config/install/core.entity_view_display.citation.su_book.default.yml
  config/install/core.entity_view_display.citation.su_thesis.default.yml
  config/install/field.field.citation.su_article_journal.su_publisher.yml
  config/install/field.field.citation.su_article_newspaper.su_publisher.yml
  config/install/field.field.citation.su_thesis.su_publisher.yml
Labels: size/s

#22 Adjusted the title size and doi field linking.
  config/install/core.entity_view_display.citation.su_article_journal.default.yml
  config/install/core.entity_view_display.citation.su_article_newspaper.default.yml
  config/install/core.entity_view_display.citation.su_book.default.yml
  config/install/core.entity_view_display.citation.su_thesis.default.yml
  config/install/field.field.citation.su_article_journal.su_publisher.yml
  config/install/field.field.citation.su_article_newspaper.su_publisher.yml
  config/install/field.field.citation.su_thesis.su_publisher.yml
  src/Entity/Citation.php
  stanford_publication.module
  tests/src/Kernel/Entity/CitationTest.php
Labels: size/s

#26 Updated views taxonomy term name depth patch
  composer.json
Labels: size/xs

#27 "8.x-1.x 8.1.1-beta.1
  CHANGELOG.md
  composer.json
  stanford_publication.info.yml
Labels: patch, size/xs

#25 D8CORE-3479: adjusting spacing for the Publication node page.
  composer.json
  config/install/views.view.stanford_publications.yml
  dist/css/component/node/stanford_publication.css
  lib/scss/component/node/stanford_publication.scss
  stanford_publication.info.yml
Labels: patch, size/m
